site_name: PyOSC Documentation
site_url: https://theatre-tools.github.io/PyOSC/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    annotation: material/arrow-right-circle

  features:
    - content.action.view
    - content.action.edit
    - search.highlight
    - search.suggest
    - navigation.instant        # mini popups
    - navigation.top            # sticky nav
    - navigation.tracking       # highlights active page
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.tooltips
    - content.code.annotate

repo_url: https://github.com/theatre-tools/PyOSC
repo_name: theatre-tools/PyOSC
edit_uri: https://github.com/theatre-tools/PyOSC/tree/main/docs/
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: theatre-tools/PyOSC
      branch: main
  - search


extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - .
        - docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - First Steps: getting-started/first-steps.md
  - Tutorials:
      - Creating a Peer: tutorials/peer.md
      - Sending Messages: tutorials/message.md
      - Receiving Messages: tutorials/dispatcher.md
      - Using Call Handlers: tutorials/call_handler.md
  - API Reference: api_reference.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md
watch:
  - docs
  - CHANGELOG.md