[project]
name = "pyosc"
version = "0.1.0"
description = "A package to add fully featured OSC support to python"
authors = [
    {name = "Morph Tollon",email = "32335272-MorphTollon@users.noreply.gitlab.com"}
]
license = "MIT License"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
